[package]
name = "xchat"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8", features = ["ws","multipart"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
tower-http = { version = "0.5", features = ["fs"] }
dotenv = "0.15.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = "0.4.42"
uuid = { version = "1", features = ["v4"] }
